CBuild::MINGW_GCC Class Reference
#include <mingw-gcc.hpp>
Public Member Functions
MINGW_GCC (std::string id)
Construct a new MINGW_GCC object.
MINGW_GCC (std::string id, std::string name)
Construct a new MINGW_GCC object.
std::string gen_out_name (std::string executable=`.exe`, std::string dyn_lib=`.dll`, std::string stat_lib=`.a`)
Generate output file name (after linking)
void call (std::vector< std::string > *args, bool force=false, bool debug=false)
Call tollchain to execute.
void run (std::vector< std::string > *args)
Run builded app.
void debug (std::vector< std::string > *args, std::vector< std::string > *pargs)
Build program in debug mode and after run gdb on it.
Public Member Functions inherited from CBuild::Toolchain
virtual std::string gen_out_name (std::string executable=`.run`, std::string dyn_lib=`.so`, std::string stat_lib=`.a`)
Generate output file name (after linking)
virtual void load_project_deps (std::string curr_path)
Load all project dependencies.
Toolchain ()
virtual ~Toolchain ()
std::string get_id ()
virtual void call (std::vector< std::string > *args, bool force=false, bool debug=false)
Call tollchain to execute.
virtual void run (std::vector< std::string > *args)
Run builded app.
virtual void debug (std::vector< std::string > *args, std::vector< std::string > *pargs)
Build program in debug mode and after run gdb on it.
virtual void clear ()
Clear all caches and builded app.
virtual void add_define (std::string define, std::string val=``)
Add new define.
virtual void add_undef (std::string define)
Add new undefine (undefine previvious define)
virtual void add_include (std::string include_path)
Add compile-time include.
virtual void add_compile_arg (std::string arg)
Directly add compiler argument.
virtual void add_link_arg (std::string arg)
Add linker arguments.
virtual void add_library_include (std::string library)
Add system library include, library include folder need to be in PATH.
virtual void add_library_dir (std::string include, std::string lib)
Add library include directory (with *.h files) and directory with library *.a and *.so/*.dll files.
virtual void add_requirment (std::string task_, CBuild::stage run_stage=CBuild::PRE)
Add required task, that task will be executed before toolchain, it can have dependecies, but toolchain can depend on multiple tasks also.
virtual void depends_on (std::string target)
This target depends on other target.
virtual void warn ()
Enable more warnings.
virtual void static_analizer ()
Enable static anlizer (very slow)
virtual void error ()
Add -Werror.
virtual void set_standart (std::string std_)
Set standart for code (-std=std_)
virtual void add_file (std::string path)
Add file for compilation.
virtual void add_folder (std::string path)
Add folder to compile path, scan is not recursive.
virtual void set_type (CBuild::build_type type)
Set the type of build.
virtual void depends_on_project (std::string path, std::string name, std::string id, std::string headers_path)
Add another CBuild project as dependency.
Protected Member Functions
void build ()
Build.
void link ()
Linking.
void link_pack ()
Linking for static libraries.
void post_link ()
After linking.
Protected Member Functions inherited from CBuild::Toolchain
virtual void pre_build ()
Before build.
virtual void post_build ()
After build.
virtual void pre_link ()
Before linking.
virtual void post_link ()
After linking.
virtual void build ()=0
Build.
virtual void link ()=0
Linking.
virtual void link_pack ()=0
Linking for static libraries.
virtual lib::map< std::string, std::string > gen_file_list (bool force_)
Generate list of files that need to be compiles.
virtual std::string gen_out_file (std::string file)
Generate output object file from input file.
virtual std::string cmd_str (std::string in)
Replace spaces by `\ `.
virtual void init ()
Initialize folder structure.
Additional Inherited Members
Protected Attributes inherited from CBuild::Toolchain
std::string name = ``
Name of output, if undefined (``), for output name used id.
std::string id
Must be initialized in derived classes.
lib::map< std::string, CBuild::stage > required
Save task id with run stage sprecified for this task.
std::vector< std::string > depends
All other targets, that is needed for this target.
std::vector< CBuild::Path > targets
Target files or folders.
std::vector< std::string > compiler_args
Compiler args (specified and generated)
std::vector< std::string > link_args
Linker args (specified and generated)
std::string compiler
Compiler command.
std::string linker
Linker command.
std::string packer
ar command for packing static libraries
CBuild::build_type build_type
Type of build.
std::vector< CBuild::Project_dependency > project_deps
Project dependencies.
std::vector< std::string > * args
Argument pointer (scratch variable)
bool force
Force argument (scratch variable)
Detailed Description
Definition at line 35 of file mingw-gcc.hpp.
Constructor & Destructor Documentation
MINGW_GCC() [1/2]
CBuild::MINGW_GCC::MINGW_GCC (std::string id) [inline]
Construct a new MINGW_GCC object.
Parameters
id Id
Definition at line 42 of file mingw-gcc.hpp.
References CBuild::Toolchain::compiler, CBuild::Toolchain::id, CBuild::Toolchain::linker, and CBuild::Toolchain::packer.
MINGW_GCC() [2/2]
CBuild::MINGW_GCC::MINGW_GCC (std::string id, std::string name) [inline]
Construct a new MINGW_GCC object.
Parameters
id Id
name Name
Definition at line 54 of file mingw-gcc.hpp.
References CBuild::Toolchain::compiler, CBuild::Toolchain::id, CBuild::Toolchain::linker, CBuild::Toolchain::name, and CBuild::Toolchain::packer.
Member Function Documentation
build()
void CBuild::MINGW_GCC::build () [inline], [protected], [virtual]
Build.
Implements CBuild::Toolchain.
Definition at line 64 of file mingw-gcc.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::compiler, CBuild::Toolchain::compiler_args, CBuild::files, CBuild::Toolchain::force, CBuild::Toolchain::gen_file_list(), and CBuild::system().
Referenced by call().
call()
void CBuild::MINGW_GCC::call (std::vector< std::string > * args, bool force = false, bool debug = false) [inline], [virtual]
Call tollchain to execute.
Parameters
args => std::vector<std::string>* -> argument for call, pointer, nonull
force => bool -> force argument, used internally
Reimplemented from CBuild::Toolchain.
Definition at line 192 of file mingw-gcc.hpp.
References CBuild::Toolchain::add_library_dir(), CBuild::Toolchain::add_library_include(), CBuild::Toolchain::add_link_arg(), CBuild::Toolchain::args, lib::map< _K, _D >::at(), build(), CBuild::Registry::CallTask(), CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBuild::Toolchain::compiler_args, debug(), CBuild::Toolchain::depends, CBuild::DYNAMIC_LIBRARY, CBuild::Toolchain::force, CBuild::Registry::GetToolchain(), CBuild::GREEN, CBuild::Toolchain::init(), link(), CBuild::Toolchain::link_args, link_pack(), CBuild::MAGENTA, CBuild::POST, CBuild::Toolchain::post_build(), post_link(), CBuild::PRE, CBuild::Toolchain::pre_build(), CBuild::Toolchain::pre_link(), CBuild::print(), CBuild::RED, CBuild::Toolchain::required, lib::map< _K, _D >::size(), and CBuild::STATIC_LIBRARY.
debug()
void CBuild::MINGW_GCC::debug (std::vector< std::string > * args, std::vector< std::string > * pargs) [inline], [virtual]
Build program in debug mode and after run gdb on it.
Parameters
args => std::vector<std::string>* -> arguments for build
pargs => std::vector<std::string>* -> arguments for run
Reimplemented from CBuild::Toolchain.
Definition at line 284 of file mingw-gcc.hpp.
References CBuild::print(), and CBuild::RED.
Referenced by call().
gen_out_name()
std::string CBuild::MINGW_GCC::gen_out_name (std::string executable = `.exe`, std::string dyn_lib = `.dll`, std::string stat_lib = `.a`) [inline], [virtual]
Generate output file name (after linking)
Returns
std::string -> File name
Reimplemented from CBuild::Toolchain.
Definition at line 156 of file mingw-gcc.hpp.
References CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBuild::Toolchain::cmd_str(), CBuild::DYNAMIC_LIBRARY, CBuild::EXECUTABLE, CBuild::Toolchain::id, and CBuild::Toolchain::name.
Referenced by link(), link_pack(), and run().
link()
void CBuild::MINGW_GCC::link () [inline], [protected], [virtual]
Linking.
Implements CBuild::Toolchain.
Definition at line 85 of file mingw-gcc.hpp.
References CBuild::Toolchain::args, CBUILD_BUILD_CACHE_DIR, CBUILD_BUILD_DIR, CBuild::fs::dir(), CBuild::files, gen_out_name(), CBuild::Toolchain::link_args, CBuild::Toolchain::linker, and CBuild::system().
Referenced by call().
link_pack()
void CBuild::MINGW_GCC::link_pack () [inline], [protected], [virtual]
Linking for static libraries.
Implements CBuild::Toolchain.
Definition at line 113 of file mingw-gcc.hpp.
References CBuild::Toolchain::args, CBUILD_BUILD_CACHE_DIR, CBUILD_BUILD_DIR, CBuild::fs::dir(), CBuild::files, gen_out_name(), CBuild::Toolchain::link_args, CBuild::Toolchain::packer, and CBuild::system().
Referenced by call().
post_link()
void CBuild::MINGW_GCC::post_link () [inline], [protected], [virtual]
After linking.
Reimplemented from CBuild::Toolchain.
Definition at line 138 of file mingw-gcc.hpp.
References CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBuild::fs::copy(), CBuild::Toolchain::depends, and CBuild::Registry::GetToolchain().
Referenced by call().
run()
void CBuild::MINGW_GCC::run (std::vector< std::string > * args) [inline], [virtual]
Run builded app.
Parameters
args => std::vector<std::string>* -> program arguments
Reimplemented from CBuild::Toolchain.
Definition at line 266 of file mingw-gcc.hpp.
References CBuild::Toolchain::args, gen_out_name(), CBuild::MAGENTA, CBuild::Toolchain::name, CBuild::print(), CBuild::RED, and CBuild::system().
The documentation for this class was generated from the following file:
CBuild/headers/build/mingw-gcc.hpp