CBuild::GCC Class Reference
#include <gcc.hpp>
Public Member Functions
GCC (std::string id)
Construct a new GCC object.
GCC (std::string id, std::string name)
Construct a new GCC object.
Public Member Functions inherited from CBuild::Toolchain
virtual std::string gen_out_name (std::string executable=`.run`, std::string dyn_lib=`.so`, std::string stat_lib=`.a`)
Generate output file name (after linking)
virtual void load_project_deps (std::string curr_path)
Load all project dependencies.
Toolchain ()
virtual ~Toolchain ()
virtual std::string get_id ()
virtual void call (std::vector< std::string > *args, bool force=false, bool debug=false)
Call tollchain to execute.
virtual void run (std::vector< std::string > *args)
Run builded app.
virtual void debug (std::vector< std::string > *args, std::vector< std::string > *pargs)
Build program in debug mode and after run gdb on it.
virtual void clear ()
Clear all caches and builded app.
virtual void add_define (std::string define, std::string val=``)
Add new define.
virtual void add_undef (std::string define)
Add new undefine (undefine previvious define)
virtual void add_include (std::string include_path)
Add compile-time include.
virtual void add_compile_arg (std::string arg)
Directly add compiler argument.
virtual void add_link_arg (std::string arg)
Add linker arguments.
virtual void add_library_include (std::string library)
Add system library include, library include folder need to be in PATH.
virtual void add_library_dir (std::string include, std::string lib)
Add library include directory (with *.h files) and directory with library *.a and *.so/*.dll files.
virtual void add_requirment (std::string task_, CBuild::stage run_stage=CBuild::PRE)
Add required task, that task will be executed before toolchain, it can have dependecies, but toolchain can depend on multiple tasks also.
virtual void depends_on (std::string target)
This target depends on other target.
virtual void warn ()
Enable more warnings.
virtual void static_analizer ()
Enable static anlizer (very slow)
virtual void error ()
Add -Werror.
virtual void set_standart (std::string std_)
Set standart for code (-std=std_)
virtual void add_file (std::string path)
Add file for compilation.
virtual void add_folder (std::string path)
Add folder to compile path, scan is not recursive.
virtual void set_type (CBuild::build_type type)
Set the type of build.
virtual void depends_on_project (std::string path, std::string name, std::string id, std::string headers_path)
Add another CBuild project as dependency.
Protected Member Functions
void build ()
Build.
void link ()
Linking.
void link_pack ()
Linking for static libraries.
Protected Member Functions inherited from CBuild::Toolchain
virtual void pre_build ()
Before build.
virtual void post_build ()
After build.
virtual void pre_link ()
Before linking.
virtual void post_link ()
After linking.
virtual void build ()=0
Build.
virtual void link ()=0
Linking.
virtual void link_pack ()=0
Linking for static libraries.
virtual lib::map< std::string, std::string > gen_file_list (bool force_)
Generate list of files that need to be compiles.
virtual std::string gen_out_file (std::string file)
Generate output object file from input file.
virtual std::string gen_hash_file (std::string file)
Generate hash file for .cpp file.
virtual std::string cmd_str (std::string in)
Replace spaces by `\ `.
virtual void init ()
Initialize folder structure.
Additional Inherited Members
Protected Attributes inherited from CBuild::Toolchain
std::string name = ``
Name of output, if undefined (``), for output name used id.
std::string id
Must be initialized in derived classes.
lib::map< std::string, CBuild::stage > required
Save task id with run stage sprecified for this task.
std::vector< std::string > depends
All other targets, that is needed for this target.
std::vector< CBuild::Path > targets
Target files or folders.
std::vector< std::string > compiler_args
Compiler args (specified and generated)
std::vector< std::string > link_args
Linker args (specified and generated)
std::string compiler
Compiler command.
std::string linker
Linker command.
std::string packer
ar command for packing static libraries
CBuild::build_type build_type
Type of build.
std::vector< CBuild::Project_dependency > project_deps
Project dependencies.
std::vector< std::string > * args
Argument pointer (scratch variable)
bool force
Force argument (scratch variable)
Detailed Description
Definition at line 33 of file gcc.hpp.
Constructor & Destructor Documentation
GCC() [1/2]
CBuild::GCC::GCC (std::string id) [inline]
Construct a new GCC object.
Parameters
id Id
Definition at line 41 of file gcc.hpp.
References CBuild::Toolchain::compiler, CBuild::Toolchain::id, CBuild::Toolchain::linker, and CBuild::Toolchain::packer.
GCC() [2/2]
CBuild::GCC::GCC (std::string id, std::string name) [inline]
Construct a new GCC object.
Parameters
id Id
name Name
Definition at line 54 of file gcc.hpp.
References CBuild::Toolchain::compiler, CBuild::Toolchain::id, CBuild::Toolchain::linker, CBuild::Toolchain::name, and CBuild::Toolchain::packer.
Member Function Documentation
build()
void CBuild::GCC::build () [inline], [protected], [virtual]
Build.
Implements CBuild::Toolchain.
Definition at line 65 of file gcc.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::compiler, CBuild::Toolchain::compiler_args, CBuild::Toolchain::force, CBuild::Toolchain::gen_file_list(), CBuild::Toolchain::gen_hash_file(), CBuild::save_hashes(), and CBuild::system().
link()
void CBuild::GCC::link () [inline], [protected], [virtual]
Linking.
Implements CBuild::Toolchain.
Definition at line 92 of file gcc.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::gen_file_list(), CBuild::Toolchain::gen_out_name(), CBuild::Toolchain::link_args, CBuild::Toolchain::linker, and CBuild::system().
link_pack()
void CBuild::GCC::link_pack () [inline], [protected], [virtual]
Linking for static libraries.
Implements CBuild::Toolchain.
Definition at line 120 of file gcc.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::gen_file_list(), CBuild::Toolchain::gen_out_name(), CBuild::Toolchain::link_args, CBuild::Toolchain::packer, and CBuild::system().
The documentation for this class was generated from the following file:
CBuild/headers/build/gcc.hpp