CBuild::line_filebuff Class Reference
#include <filebuff.hpp>
Public Member Functions
line_filebuff (std::string file, bool refresh=false, bool new_file=false)
char get_char (unsigned int pos)
Get character from file, return -1 on error.
std::string get_str (unsigned int pos, unsigned int size)
Get sequence of characters from file.
void set_char (char ch, unsigned int pos)
Set character in file.
void set_str (std::string str, unsigned int pos)
Set string in file.
void del_char (unsigned int pos)
Remove character from file.
void del_str (unsigned int pos, unsigned int size)
Remove sequence of characters from file.
std::string get_line (unsigned int pos)
Get line from buffer.
void set_line (std::string str, unsigned int pos)
Set line in file.
void del_line (unsigned int pos)
Delete line from file.
void update ()
Update file/buffer based on internal state variable.
Public Member Functions inherited from CBuild::filebuff
filebuff (std::string file, bool autorefresh=true)
Create filebuffer, simply store some vars.
virtual char get_char (unsigned int pos)=0
Get character from file, return -1 on error.
virtual std::string get_str (unsigned int pos, unsigned int size)=0
Get sequence of characters from file.
virtual void set_char (char ch, unsigned int pos)=0
Set character in file.
virtual void set_str (std::string str, unsigned int pos)=0
Set string in file.
virtual void del_char (unsigned int pos)=0
Remove character from file.
virtual void del_str (unsigned int pos, unsigned int size)=0
Remove sequence of characters from file.
virtual void update ()=0
Update file/buffer based on internal state variable.
CBuild::buffer_state get_state ()
Get state of file.
Protected Member Functions
void load_buffer ()
Load buffer from file.
void save_buffer ()
Save buffer to file.
virtual void load_buffer ()=0
Load buffer from file.
virtual void save_buffer ()=0
Save buffer to file.
Protected Attributes
std::list< std::string > buff
Protected Attributes inherited from CBuild::filebuff
std::string path
Path to file.
bool autorefresh
Does file need to be automaticly.
CBuild::buffer_state state
Currennt state of buffer. All operation that change buffer need to set state to CBuild::BUFFER_NEWER or update file based on autorefresh variable. All function that update buffer/file and synchronise it need to set state to CBuild::MATCH.
Detailed Description
Definition at line 170 of file filebuff.hpp.
Constructor & Destructor Documentation
line_filebuff()
CBuild::line_filebuff::line_filebuff (std::string file, bool refresh = false, bool new_file = false) [inline]
Definition at line 190 of file filebuff.hpp.
References load_buffer().
Member Function Documentation
del_char()
void CBuild::line_filebuff::del_char (unsigned int pos) [inline], [virtual]
Remove character from file.
Parameters
pos => unsigned int -> Position of character thet need to be removed
Implements CBuild::filebuff.
Definition at line 312 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
del_line()
void CBuild::line_filebuff::del_line (unsigned int pos) [inline]
Delete line from file.
Parameters
pos => unsigned int -> Linenumber
Definition at line 426 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
del_str()
void CBuild::line_filebuff::del_str (unsigned int pos, unsigned int size) [inline], [virtual]
Remove sequence of characters from file.
Parameters
pos => unsigned int -> Postion of first character of sequence
size => unsigned int -> Number of character to remove
Implements CBuild::filebuff.
Definition at line 337 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
get_char()
char CBuild::line_filebuff::get_char (unsigned int pos) [inline], [virtual]
Get character from file, return -1 on error.
Parameters
pos => unsigned int -> Position of character in file
Returns
char -> Symbol
Implements CBuild::filebuff.
Definition at line 197 of file filebuff.hpp.
get_line()
std::string CBuild::line_filebuff::get_line (unsigned int pos) [inline]
Get line from buffer.
Parameters
pos => unsigned int -> Linenumber
Returns
std::string -> Line
Definition at line 400 of file filebuff.hpp.
get_str()
std::string CBuild::line_filebuff::get_str (unsigned int pos, unsigned int size) [inline], [virtual]
Get sequence of characters from file.
Parameters
pos => unsigned int -> Postion of first character of line
size => unsigned int -> Number of characters in line
Returns
std::string -> String
Implements CBuild::filebuff.
Definition at line 208 of file filebuff.hpp.
load_buffer()
void CBuild::line_filebuff::load_buffer () [inline], [protected], [virtual]
Load buffer from file.
Implements CBuild::filebuff.
Definition at line 173 of file filebuff.hpp.
References CBuild::MATCH, CBuild::filebuff::path, and CBuild::filebuff::state.
Referenced by line_filebuff(), and update().
save_buffer()
void CBuild::line_filebuff::save_buffer () [inline], [protected], [virtual]
Save buffer to file.
Implements CBuild::filebuff.
Definition at line 182 of file filebuff.hpp.
References CBuild::filebuff::path.
Referenced by del_char(), del_line(), del_str(), set_char(), set_line(), set_str(), and update().
set_char()
void CBuild::line_filebuff::set_char (char ch, unsigned int pos) [inline], [virtual]
Set character in file.
Parameters
ch => char -> Character
pos => unsigned int -> Character will be appended to file on this pos
Implements CBuild::filebuff.
Definition at line 252 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
set_line()
void CBuild::line_filebuff::set_line (std::string str, unsigned int pos) [inline]
Set line in file.
Parameters
str => std::string -> Line
pos => unsigned int -> Linenumber of new line
Definition at line 411 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
set_str()
void CBuild::line_filebuff::set_str (std::string str, unsigned int pos) [inline], [virtual]
Set string in file.
Parameters
ch => std::string -> String
pos => unsigned int -> String will be appended to file on this pos
Implements CBuild::filebuff.
Definition at line 278 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, CBuild::parse_lines(), save_buffer(), and CBuild::filebuff::state.
update()
void CBuild::line_filebuff::update () [inline], [virtual]
Update file/buffer based on internal state variable.
Implements CBuild::filebuff.
Definition at line 436 of file filebuff.hpp.
References CBuild::BUFFER_NEWER, CBuild::FILE_NEWER, load_buffer(), CBuild::MATCH, save_buffer(), and CBuild::filebuff::state.
Member Data Documentation
buff
std::list<std::string> CBuild::line_filebuff::buff [protected]
Definition at line 172 of file filebuff.hpp.
The documentation for this class was generated from the following file:
CBuild/headers/filebuff.hpp