CBuild::Toolchain Class Reference
Toolchain class.
#include <Build.hpp>
Public Member Functions
virtual std::string gen_out_name (std::string executable=`.run`, std::string dyn_lib=`.so`, std::string stat_lib=`.a`)
Generate output file name (after linking)
Toolchain ()
~Toolchain ()
virtual std::string get_id ()
virtual void call (std::vector< std::string > *args, bool force=false, bool debug=false)
Call tollchain to execute.
virtual void run (std::vector< std::string > *args)
Run builded app.
virtual void debug (std::vector< std::string > *args, std::vector< std::string > *pargs)
Build program in debug mode and after run gdb on it.
virtual void clear ()
Clear all caches and builded app.
virtual void add_define (std::string define, std::string val=``)
Add new define.
virtual void add_undef (std::string define)
Add new undefine (undefine previvious define)
virtual void add_include (std::string include_path)
Add compile-time include.
virtual void add_compile_arg (std::string arg)
Directly add compiler argument.
virtual void add_link_arg (std::string arg)
Add linker arguments.
virtual void add_library_include (std::string library)
Add system library include, library include folder need to be in PATH.
virtual void add_library_dir (std::string include, std::string lib)
Add library include directory (with *.h files) and directory with library *.a and *.so/*.dll files.
virtual void add_requirment (std::string task_, CBuild::stage run_stage=CBuild::PRE)
Add required task, that task will be executed before toolchain, it can have dependecies, but toolchain can depend on multiple tasks also.
virtual void depends_on (std::string target)
This target depends on other target.
virtual void warn ()
Enable more warnings.
virtual void static_analizer ()
Enable static anlizer (very slow)
virtual void error ()
Add -Werror.
virtual void set_standart (std::string std_)
Set standart for code (-std=std_)
virtual void add_file (std::string path)
Add file for compilation.
virtual void add_folder (std::string path)
Add folder to compile path, scan is not recursive.
virtual void set_type (CBuild::build_type type)
Set the type of build.
Protected Member Functions
virtual void pre_build ()
Before build.
virtual void post_build ()
After build.
virtual void pre_link ()
Before linking.
virtual void post_link ()
After linking.
virtual void build ()=0
Build.
virtual void link ()=0
Linking.
virtual void link_pack ()=0
Linking for static libraries.
virtual lib::map< std::string, std::string > gen_file_list (bool force_)
Generate list of files that need to be compiles.
virtual std::string gen_out_file (std::string file)
Generate output object file from input file.
virtual std::string gen_hash_file (std::string file)
Generate hash file for .cpp file.
virtual std::string cmd_str (std::string in)
Replace spaces by `\ `.
virtual void init ()
Initialize folder structure.
Protected Attributes
std::string name = ``
Name of output, if undefined (``), for output name used id.
std::string id
Must be initialized in derived classes.
lib::map< std::string, CBuild::stage > required
Save task id with run stage sprecified for this task.
std::vector< std::string > depends
All other targets, that is needed for this target.
std::vector< CBuild::Path > targets
Target files or folders.
std::vector< std::string > compiler_args
Compiler args (specified and generated)
std::vector< std::string > link_args
Linker args (specified and generated)
std::string compiler
Compiler command.
std::string linker
Linker command.
std::string packer
ar command for packing static libraries
std::vector< std::string > * args
Argument pointer (scratch variable)
bool force
Force argument (scratch variable)
CBuild::build_type build_type
Type of build.
Detailed Description
Toolchain class.
Definition at line 55 of file Build.hpp.
Constructor & Destructor Documentation
Toolchain()
CBuild::Toolchain::Toolchain () [inline]
Definition at line 182 of file Build.hpp.
 Toolchain()
CBuild::Toolchain::~Toolchain () [inline]
Definition at line 183 of file Build.hpp.
Member Function Documentation
add_compile_arg()
void CBuild::Toolchain::add_compile_arg (std::string arg) [virtual]
Directly add compiler argument.
Parameters
arg => std:string -> argument, directly passed to compiler
Definition at line 39 of file Build.cpp.
References compiler_args.
add_define()
void CBuild::Toolchain::add_define (std::string define, std::string val = ``) [virtual]
Add new define.
Parameters
define => std:string -> Define name
arg => std:string -> Value for define, default - ``
Definition at line 55 of file Build.cpp.
add_file()
void CBuild::Toolchain::add_file (std::string path) [virtual]
Add file for compilation.
Parameters
path => std::string -> Path to file
Definition at line 168 of file Build.cpp.
References CBuild::Path::folder, and CBuild::Path::path.
add_folder()
void CBuild::Toolchain::add_folder (std::string path) [virtual]
Add folder to compile path, scan is not recursive.
Parameters
path => std::string -> Path to folder
Definition at line 181 of file Build.cpp.
References CBuild::Path::folder, and CBuild::Path::path.
add_include()
void CBuild::Toolchain::add_include (std::string include_path) [virtual]
Add compile-time include.
Parameters
include_path => std:string -> path for include
Definition at line 83 of file Build.cpp.
add_library_dir()
void CBuild::Toolchain::add_library_dir (std::string include, std::string lib) [virtual]
Add library include directory (with *.h files) and directory with library *.a and *.so/*.dll files.
Parameters
include => std:string -> include dir, will be used as -I<include>
lib => std:string -> library dir, will be used as -L<lib>
Definition at line 107 of file Build.cpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
add_library_include()
void CBuild::Toolchain::add_library_include (std::string library) [virtual]
Add system library include, library include folder need to be in PATH.
Parameters
library => std:string -> library name, will be used as -l<library>
Definition at line 95 of file Build.cpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
add_link_arg()
void CBuild::Toolchain::add_link_arg (std::string arg) [virtual]
Add linker arguments.
Parameters
arg => std:string -> argument, directly passed to compiler
Definition at line 47 of file Build.cpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
add_requirment()
void CBuild::Toolchain::add_requirment (std::string task_, CBuild::stage run_stage = CBuild::PRE) [virtual]
Add required task, that task will be executed before toolchain, it can have dependecies, but toolchain can depend on multiple tasks also.
Parameters
task_ => std:string -> task id
run_stage => CBuild::stage -> run stage of task
Definition at line 123 of file Build.cpp.
add_undef()
void CBuild::Toolchain::add_undef (std::string define) [virtual]
Add new undefine (undefine previvious define)
Parameters
define => std::string -> Define name
Definition at line 72 of file Build.cpp.
build()
virtual void CBuild::Toolchain::build () [protected], [pure virtual]
Build.
Implemented in CBuild::GXX, CBuild::GCC, CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
call()
void CBuild::Toolchain::call (std::vector< std::string > * args, bool force = false, bool debug = false) [virtual]
Call tollchain to execute.
Parameters
args => std::vector<std::string>* -> argument for call, pointer, nonull
force => bool -> force argument, used internally
Reimplemented in CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
Definition at line 428 of file Build.cpp.
References CBuild::Registry::CallTask(), CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBuild::DYNAMIC_LIBRARY, CBuild::Registry::GetToolchain(), CBuild::GREEN, CBuild::MAGENTA, CBuild::POST, CBuild::PRE, CBuild::print(), CBuild::RED, and CBuild::STATIC_LIBRARY.
Referenced by CBuild::loop().
clear()
void CBuild::Toolchain::clear () [virtual]
Clear all caches and builded app.
Definition at line 576 of file Build.cpp.
References CBUILD_BUILD_DIR, and CBuild::system().
Referenced by CBuild::loop().
cmd_str()
std::string CBuild::Toolchain::cmd_str (std::string in) [protected], [virtual]
Replace spaces by `\ `.
Parameters
in => std::string -> input string
Returns
std::string Returned string
Definition at line 386 of file Build.cpp.
Referenced by CBuild::MINGW_GXX::gen_out_name(), and CBuild::MINGW_GCC::gen_out_name().
debug()
void CBuild::Toolchain::debug (std::vector< std::string > * args, std::vector< std::string > * pargs) [virtual]
Build program in debug mode and after run gdb on it.
Parameters
args => std::vector<std::string>* -> arguments for build
pargs => std::vector<std::string>* -> arguments for run
Reimplemented in CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
Definition at line 550 of file Build.cpp.
References CBuild::GREEN, CBuild::MAGENTA, CBuild::print(), CBuild::RED, and CBuild::system().
Referenced by CBuild::loop().
depends_on()
void CBuild::Toolchain::depends_on (std::string target) [virtual]
This target depends on other target.
Parameters
target => std::string -> Other target id
Definition at line 162 of file Build.cpp.
error()
void CBuild::Toolchain::error () [virtual]
Add -Werror.
Definition at line 144 of file Build.cpp.
gen_file_list()
lib::map< std::string, std::string > CBuild::Toolchain::gen_file_list (bool force_) [protected], [virtual]
Generate list of files that need to be compiles.
Returns
lib::map<std::string, std::string> -> list of files, key - code, value - object
Definition at line 233 of file Build.cpp.
References CBuild::fs::create(), CBuild::fs::dir(), CBuild::fs::exists(), CBuild::fs::FILE, CBuild::load_hash(), and lib::map< _K, _D >::push_back().
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::GXX::link(), CBuild::GCC::link(), CBuild::MINGW_GXX::link(), CBuild::MINGW_GCC::link(), CBuild::GXX::link_pack(), CBuild::GCC::link_pack(), CBuild::MINGW_GXX::link_pack(), and CBuild::MINGW_GCC::link_pack().
gen_hash_file()
std::string CBuild::Toolchain::gen_hash_file (std::string file) [protected], [virtual]
Generate hash file for .cpp file.
Parameters
file => std::string -> input file
Returns
std::string -> file path
Definition at line 214 of file Build.cpp.
References CBUILD_BUILD_DIR, and CBUILD_HASH_DIR.
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), and CBuild::MINGW_GCC::build().
gen_out_file()
std::string CBuild::Toolchain::gen_out_file (std::string file) [protected], [virtual]
Generate output object file from input file.
Parameters
file => std::string -> input file
Returns
std::string -> file path
Definition at line 195 of file Build.cpp.
References CBUILD_BUILD_CACHE_DIR, and CBUILD_BUILD_DIR.
gen_out_name()
std::string CBuild::Toolchain::gen_out_name (std::string executable = `.run`, std::string dyn_lib = `.so`, std::string stat_lib = `.a`) [virtual]
Generate output file name (after linking)
Returns
std::string -> File name
Reimplemented in CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
Definition at line 328 of file Build.cpp.
References CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBuild::DYNAMIC_LIBRARY, and CBuild::EXECUTABLE.
Referenced by CBuild::GXX::link(), CBuild::GCC::link(), CBuild::GXX::link_pack(), and CBuild::GCC::link_pack().
get_id()
virtual std::string CBuild::Toolchain::get_id () [inline], [virtual]
Definition at line 184 of file Build.hpp.
References id.
Referenced by CBuild::Registry::RegisterTarget().
init()
void CBuild::Toolchain::init () [protected], [virtual]
Initialize folder structure.
Definition at line 400 of file Build.cpp.
References CBUILD_BUILD_CACHE_DIR, CBUILD_BUILD_DIR, CBUILD_BUILD_OUT_DIR, CBUILD_HASH_DIR, CBuild::fs::create(), CBuild::fs::DIR, and CBuild::fs::exists().
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
link()
virtual void CBuild::Toolchain::link () [protected], [pure virtual]
Linking.
Implemented in CBuild::GXX, CBuild::GCC, CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
link_pack()
virtual void CBuild::Toolchain::link_pack () [protected], [pure virtual]
Linking for static libraries.
Implemented in CBuild::GXX, CBuild::GCC, CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
post_build()
virtual void CBuild::Toolchain::post_build () [inline], [protected], [virtual]
After build.
Definition at line 120 of file Build.hpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
post_link()
virtual void CBuild::Toolchain::post_link () [inline], [protected], [virtual]
After linking.
Reimplemented in CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
Definition at line 128 of file Build.hpp.
pre_build()
virtual void CBuild::Toolchain::pre_build () [inline], [protected], [virtual]
Before build.
Definition at line 116 of file Build.hpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
pre_link()
virtual void CBuild::Toolchain::pre_link () [inline], [protected], [virtual]
Before linking.
Definition at line 124 of file Build.hpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
run()
void CBuild::Toolchain::run (std::vector< std::string > * args) [virtual]
Run builded app.
Parameters
args => std::vector<std::string>* -> program arguments
Reimplemented in CBuild::MINGW_GXX, and CBuild::MINGW_GCC.
Definition at line 527 of file Build.cpp.
References CBuild::MAGENTA, CBuild::print(), CBuild::RED, and CBuild::system().
Referenced by CBuild::loop().
set_standart()
void CBuild::Toolchain::set_standart (std::string std_) [virtual]
Set standart for code (-std=std_)
Parameters
std_ => std::string -> Stadart name
Definition at line 149 of file Build.cpp.
set_type()
void CBuild::Toolchain::set_type (CBuild::build_type type) [virtual]
Set the type of build.
Parameters
type Build type
Definition at line 158 of file Build.cpp.
static_analizer()
void CBuild::Toolchain::static_analizer () [virtual]
Enable static anlizer (very slow)
Definition at line 138 of file Build.cpp.
warn()
void CBuild::Toolchain::warn () [virtual]
Enable more warnings.
Definition at line 131 of file Build.cpp.
Member Data Documentation
args
std::vector<std::string>* CBuild::Toolchain::args [protected]
Argument pointer (scratch variable)
Definition at line 102 of file Build.hpp.
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::MINGW_GXX::call(), CBuild::MINGW_GCC::call(), CBuild::GXX::link(), CBuild::GCC::link(), CBuild::MINGW_GXX::link(), CBuild::MINGW_GCC::link(), CBuild::GXX::link_pack(), CBuild::GCC::link_pack(), CBuild::MINGW_GXX::link_pack(), CBuild::MINGW_GCC::link_pack(), CBuild::MINGW_GXX::run(), and CBuild::MINGW_GCC::run().
build_type
CBuild::build_type CBuild::Toolchain::build_type [protected]
Type of build.
Definition at line 110 of file Build.hpp.
compiler
std::string CBuild::Toolchain::compiler [protected]
Compiler command.
Definition at line 90 of file Build.hpp.
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::GCC::GCC(), CBuild::GXX::GXX(), CBuild::MINGW_GCC::MINGW_GCC(), and CBuild::MINGW_GXX::MINGW_GXX().
compiler_args
std::vector<std::string> CBuild::Toolchain::compiler_args [protected]
Compiler args (specified and generated)
Definition at line 82 of file Build.hpp.
Referenced by add_compile_arg(), CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
depends
std::vector<std::string> CBuild::Toolchain::depends [protected]
All other targets, that is needed for this target.
Definition at line 74 of file Build.hpp.
Referenced by CBuild::MINGW_GXX::call(), CBuild::MINGW_GCC::call(), CBuild::MINGW_GXX::post_link(), and CBuild::MINGW_GCC::post_link().
force
bool CBuild::Toolchain::force [protected]
Force argument (scratch variable)
Definition at line 106 of file Build.hpp.
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
id
std::string CBuild::Toolchain::id [protected]
Must be initialized in derived classes.
Definition at line 66 of file Build.hpp.
Referenced by CBuild::GCC::GCC(), CBuild::MINGW_GXX::gen_out_name(), CBuild::MINGW_GCC::gen_out_name(), get_id(), CBuild::GXX::GXX(), CBuild::MINGW_GCC::MINGW_GCC(), and CBuild::MINGW_GXX::MINGW_GXX().
link_args
std::vector<std::string> CBuild::Toolchain::link_args [protected]
Linker args (specified and generated)
Definition at line 86 of file Build.hpp.
Referenced by CBuild::MINGW_GXX::call(), CBuild::MINGW_GCC::call(), CBuild::GXX::link(), CBuild::GCC::link(), CBuild::MINGW_GXX::link(), CBuild::MINGW_GCC::link(), CBuild::GXX::link_pack(), CBuild::GCC::link_pack(), CBuild::MINGW_GXX::link_pack(), and CBuild::MINGW_GCC::link_pack().
linker
std::string CBuild::Toolchain::linker [protected]
Linker command.
Definition at line 94 of file Build.hpp.
Referenced by CBuild::GCC::GCC(), CBuild::GXX::GXX(), CBuild::GXX::link(), CBuild::GCC::link(), CBuild::MINGW_GXX::link(), CBuild::MINGW_GCC::link(), CBuild::MINGW_GCC::MINGW_GCC(), and CBuild::MINGW_GXX::MINGW_GXX().
name
std::string CBuild::Toolchain::name = `` [protected]
Name of output, if undefined (``), for output name used id.
Definition at line 61 of file Build.hpp.
Referenced by CBuild::GCC::GCC(), CBuild::MINGW_GXX::gen_out_name(), CBuild::MINGW_GCC::gen_out_name(), CBuild::GXX::GXX(), CBuild::MINGW_GCC::MINGW_GCC(), CBuild::MINGW_GXX::MINGW_GXX(), CBuild::MINGW_GXX::run(), and CBuild::MINGW_GCC::run().
packer
std::string CBuild::Toolchain::packer [protected]
ar command for packing static libraries
Definition at line 98 of file Build.hpp.
Referenced by CBuild::GCC::GCC(), CBuild::GXX::GXX(), CBuild::GXX::link_pack(), CBuild::GCC::link_pack(), CBuild::MINGW_GXX::link_pack(), CBuild::MINGW_GCC::link_pack(), CBuild::MINGW_GCC::MINGW_GCC(), and CBuild::MINGW_GXX::MINGW_GXX().
required
lib::map<std::string, CBuild::stage> CBuild::Toolchain::required [protected]
Save task id with run stage sprecified for this task.
Definition at line 70 of file Build.hpp.
Referenced by CBuild::MINGW_GXX::call(), and CBuild::MINGW_GCC::call().
targets
std::vector<CBuild::Path> CBuild::Toolchain::targets [protected]
Target files or folders.
Definition at line 78 of file Build.hpp.
The documentation for this class was generated from the following files:
CBuild/headers/build/Build.hpp
CBuild/CBuild/src/Build.cpp