CBuild::GXX Class Reference
#include <g++.hpp>
Public Member Functions
GXX (std::string id)
Construct a new GXX object.
GXX (std::string id, std::string name)
Construct a new GXX object.
Protected Member Functions
void build ()
Build.
void link ()
Linking.
void link_pack ()
Linking for static libraries.
Additional Inherited Members
Detailed Description
Definition at line 33 of file g++.hpp.
Constructor & Destructor Documentation
GXX() [1/2]
CBuild::GXX::GXX (std::string id) [inline]
Construct a new GXX object.
Parameters
id Id
Definition at line 41 of file g++.hpp.
References CBuild::Toolchain::compiler, CBuild::Toolchain::id, CBuild::Toolchain::linker, and CBuild::Toolchain::packer.
GXX() [2/2]
CBuild::GXX::GXX (std::string id, std::string name) [inline]
Construct a new GXX object.
Parameters
id Id
name Name
Definition at line 55 of file g++.hpp.
References CBuild::Toolchain::compiler, CBuild::Toolchain::id, CBuild::Toolchain::linker, CBuild::Toolchain::name, and CBuild::Toolchain::packer.
Member Function Documentation
build()
void CBuild::GXX::build () [inline], [protected], [virtual]
Build.
Implements CBuild::Toolchain.
Definition at line 66 of file g++.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::compiler, CBuild::Toolchain::compiler_args, CBuild::Toolchain::force, CBuild::Toolchain::gen_file_list(), CBuild::Toolchain::gen_hash_file(), CBuild::save_hashes(), and CBuild::system().
link()
void CBuild::GXX::link () [inline], [protected], [virtual]
Linking.
Implements CBuild::Toolchain.
Definition at line 100 of file g++.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::gen_file_list(), CBuild::Toolchain::gen_out_name(), CBuild::Toolchain::link_args, CBuild::Toolchain::linker, and CBuild::system().
link_pack()
void CBuild::GXX::link_pack () [inline], [protected], [virtual]
Linking for static libraries.
Implements CBuild::Toolchain.
Definition at line 132 of file g++.hpp.
References CBuild::Toolchain::args, CBuild::Toolchain::gen_file_list(), CBuild::Toolchain::gen_out_name(), CBuild::Toolchain::link_args, CBuild::Toolchain::packer, and CBuild::system().
The documentation for this class was generated from the following file:
CBuild/headers/build/g++.hpp