CBuild::str_filebuff Class Reference
#include <filebuff.hpp>
Public Member Functions
str_filebuff (std::string file, bool refresh=false, bool new_file=false)
char get_char (unsigned int pos)
Get character from file, return -1 on error.
std::string get_str (unsigned int pos, unsigned int size)
Get sequence of characters from file.
void set_char (char ch, unsigned int pos)
Set character in file.
void set_str (std::string str, unsigned int pos)
Set string in file.
void del_char (unsigned int pos)
Remove character from file.
void del_str (unsigned int pos, unsigned int size)
Remove sequence of characters from file.
void update ()
Update file/buffer based on internal state variable.
Public Member Functions inherited from CBuild::filebuff
filebuff (std::string file, bool autorefresh=true)
Create filebuffer, simply store some vars.
virtual char get_char (unsigned int pos)=0
Get character from file, return -1 on error.
virtual std::string get_str (unsigned int pos, unsigned int size)=0
Get sequence of characters from file.
virtual void set_char (char ch, unsigned int pos)=0
Set character in file.
virtual void set_str (std::string str, unsigned int pos)=0
Set string in file.
virtual void del_char (unsigned int pos)=0
Remove character from file.
virtual void del_str (unsigned int pos, unsigned int size)=0
Remove sequence of characters from file.
virtual void update ()=0
Update file/buffer based on internal state variable.
CBuild::buffer_state get_state ()
Get state of file.
Protected Member Functions
void load_buffer ()
Load buffer from file.
void save_buffer ()
Save buffer to file.
virtual void load_buffer ()=0
Load buffer from file.
virtual void save_buffer ()=0
Save buffer to file.
Protected Attributes
std::string buff
Protected Attributes inherited from CBuild::filebuff
std::string path
Path to file.
bool autorefresh
Does file need to be automaticly.
CBuild::buffer_state state
Currennt state of buffer. All operation that change buffer need to set state to CBuild::BUFFER_NEWER or update file based on autorefresh variable. All function that update buffer/file and synchronise it need to set state to CBuild::MATCH.
Detailed Description
Definition at line 450 of file filebuff.hpp.
Constructor & Destructor Documentation
str_filebuff()
CBuild::str_filebuff::str_filebuff (std::string file, bool refresh = false, bool new_file = false) [inline]
Definition at line 467 of file filebuff.hpp.
References load_buffer().
Member Function Documentation
del_char()
void CBuild::str_filebuff::del_char (unsigned int pos) [inline], [virtual]
Remove character from file.
Parameters
pos => unsigned int -> Position of character thet need to be removed
Implements CBuild::filebuff.
Definition at line 514 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
del_str()
void CBuild::str_filebuff::del_str (unsigned int pos, unsigned int size) [inline], [virtual]
Remove sequence of characters from file.
Parameters
pos => unsigned int -> Postion of first character of sequence
size => unsigned int -> Number of character to remove
Implements CBuild::filebuff.
Definition at line 525 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
get_char()
char CBuild::str_filebuff::get_char (unsigned int pos) [inline], [virtual]
Get character from file, return -1 on error.
Parameters
pos => unsigned int -> Position of character in file
Returns
char -> Symbol
Implements CBuild::filebuff.
Definition at line 474 of file filebuff.hpp.
References buff.
get_str()
std::string CBuild::str_filebuff::get_str (unsigned int pos, unsigned int size) [inline], [virtual]
Get sequence of characters from file.
Parameters
pos => unsigned int -> Postion of first character of line
size => unsigned int -> Number of characters in line
Returns
std::string -> String
Implements CBuild::filebuff.
Definition at line 481 of file filebuff.hpp.
References buff.
load_buffer()
void CBuild::str_filebuff::load_buffer () [inline], [protected], [virtual]
Load buffer from file.
Implements CBuild::filebuff.
Definition at line 453 of file filebuff.hpp.
References CBuild::MATCH, CBuild::filebuff::path, and CBuild::filebuff::state.
Referenced by str_filebuff(), and update().
save_buffer()
void CBuild::str_filebuff::save_buffer () [inline], [protected], [virtual]
Save buffer to file.
Implements CBuild::filebuff.
Definition at line 460 of file filebuff.hpp.
References CBuild::MATCH, CBuild::filebuff::path, and CBuild::filebuff::state.
Referenced by del_char(), del_str(), set_char(), set_str(), and update().
set_char()
void CBuild::str_filebuff::set_char (char ch, unsigned int pos) [inline], [virtual]
Set character in file.
Parameters
ch => char -> Character
pos => unsigned int -> Character will be appended to file on this pos
Implements CBuild::filebuff.
Definition at line 490 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, buff, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
set_str()
void CBuild::str_filebuff::set_str (std::string str, unsigned int pos) [inline], [virtual]
Set string in file.
Parameters
ch => std::string -> String
pos => unsigned int -> String will be appended to file on this pos
Implements CBuild::filebuff.
Definition at line 503 of file filebuff.hpp.
References CBuild::filebuff::autorefresh, CBuild::BUFFER_NEWER, save_buffer(), and CBuild::filebuff::state.
update()
void CBuild::str_filebuff::update () [inline], [virtual]
Update file/buffer based on internal state variable.
Implements CBuild::filebuff.
Definition at line 536 of file filebuff.hpp.
References CBuild::BUFFER_NEWER, CBuild::FILE_NEWER, load_buffer(), CBuild::MATCH, save_buffer(), and CBuild::filebuff::state.
Member Data Documentation
buff
std::string CBuild::str_filebuff::buff [protected]
Definition at line 452 of file filebuff.hpp.
Referenced by get_char(), get_str(), and set_char().
The documentation for this class was generated from the following file:
CBuild/headers/filebuff.hpp