CBuild/CBuild/src/hash.cpp File Reference
SHA256 implementation.
#include `fstream`
#include `iostream`
#include `sstream`
#include `iomanip`
#include `openssl/sha.h`
#include `string`
#include `vector`
#include `../../headers/hash.hpp`
Functions
std::string sha256 (const std::string str)
Variables
std::vector< std::string > changed
Detailed Description
SHA256 implementation.
Author
WolodiaM (w_melnyk@outlook.com)
Version
1.0
Date
2023-02-13
@license GPL v3.0 or later
Copyright (C) 2023 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Definition in file hash.cpp.
Function Documentation
sha256()
std::string sha256 (const std::string str)
Definition at line 34 of file hash.cpp.
References sha256().
Referenced by CBuild::hash_match_store(), CBuild::load_hash(), CBuild::save_hashes(), and sha256().
Variable Documentation
changed
std::vector<std::string> changed
Definition at line 51 of file hash.cpp.