CBuild::Registry Namespace Reference
Functions
void init ()
Internal init.
void RegistryTask (CBuild::Task *task)
Register new task.
void CallTask (std::string name, std::vector< std::string > args)
Run tasks.
void RegisterTarget (CBuild::Toolchain *target)
Register new target for build.
CBuild::Toolchain * GetToolchain (std::string name, bool force=false)
Get the registered toolchain.
lib::map< std::string, CBuild::Toolchain * > GetTargets ()
Get list of all targets.
void RegisterKeyword (std::string key, CBuild::Task *func)
Register new keyord for parsing, ! Dangerous, owerwriting existing keywords can lead to undefined behaviours.
lib::map< std::string, std::string > GetKeywordsList ()
Get list of all user registered keywords.
void SetRebuildName (std::string _name)
Set the rebuilt CBuild executable name.
void AddLinkArg (std::string arg)
Add linker arg for CBuild rebuild.
void AddCompileArg (std::string arg)
Add compiler argument for CBuild rebuild.
std::string GetRebuildArgs ()
Get the rebuild args for CBuild executable.
Variables
CBuild::Help help
CBuild::Init initw
lib::map< std::string, CBuild::Task * > tasks
lib::map< std::string, bool > task_executed
lib::map< std::string, CBuild::Toolchain * > targets
lib::map< std::string, bool > target_executed
lib::map< std::string, std::string > keywords
std::string name = `CBuild.run`
std::vector< std::string > cargs
std::vector< std::string > largs
Function Documentation
AddCompileArg()
void CBuild::Registry::AddCompileArg (std::string arg)
Add compiler argument for CBuild rebuild.
Parameters
arg => std::string -> raw argument
Definition at line 217 of file register.cpp.
AddLinkArg()
void CBuild::Registry::AddLinkArg (std::string arg)
Add linker arg for CBuild rebuild.
Parameters
arg => std::string -> raw argument
Definition at line 212 of file register.cpp.
CallTask()
void CBuild::Registry::CallTask (std::string name, std::vector< std::string > args)
Run tasks.
Parameters
name => std::string -> Name of task
args => std::vector<std::string> -> Arguments for task
Definition at line 133 of file register.cpp.
References name.
Referenced by CBuild::Toolchain::call(), CBuild::MINGW_GXX::call(), CBuild::MINGW_GCC::call(), and CBuild::loop().
GetKeywordsList()
lib::map< std::string, std::string > CBuild::Registry::GetKeywordsList ()
Get list of all user registered keywords.
Returns
lib::map<std::string, std::string> where key - keyword, value - task id to call
Definition at line 201 of file register.cpp.
GetRebuildArgs()
std::string CBuild::Registry::GetRebuildArgs ()
Get the rebuild args for CBuild executable.
Returns
std::string -> formatted arguments
Definition at line 222 of file register.cpp.
Referenced by CBuild::rebuild().
GetTargets()
lib::map< std::string, CBuild::Toolchain * > CBuild::Registry::GetTargets ()
Get list of all targets.
Returns
lib::map<std::string, CBuild::Toolchain*>
Definition at line 189 of file register.cpp.
GetToolchain()
CBuild::Toolchain * CBuild::Registry::GetToolchain (std::string name, bool force = false)
Get the registered toolchain.
Parameters
name => std::string -> target id
force => bool -> default = false, if true does not look in list of executed toolchains
Returns
CBuild::Toolchain* -> pointer to toolchain or null if target with given id does not exists
Definition at line 163 of file register.cpp.
References name.
Referenced by CBuild::Toolchain::call(), CBuild::MINGW_GXX::call(), CBuild::MINGW_GCC::call(), CBuild::loop(), CBuild::MINGW_GXX::post_link(), and CBuild::MINGW_GCC::post_link().
init()
void CBuild::Registry::init ()
Internal init.
Definition at line 119 of file register.cpp.
References help, and initw.
Referenced by CBuild::parse().
RegisterKeyword()
void CBuild::Registry::RegisterKeyword (std::string key, CBuild::Task * func)
Register new keyord for parsing, ! Dangerous, owerwriting existing keywords can lead to undefined behaviours.
Parameters
key => std::string -> new keyword
func => Cbuild::Task -> task, associated with keyword
Definition at line 194 of file register.cpp.
References CBuild::Task::self_name().
RegisterTarget()
void CBuild::Registry::RegisterTarget (CBuild::Toolchain * target)
Register new target for build.
Parameters
target => CBuild::Toolchain* -> Pointer to staticly allocated class that extends CBuild::Toolchain
Definition at line 156 of file register.cpp.
References CBuild::Toolchain::get_id().
RegistryTask()
void CBuild::Registry::RegistryTask (CBuild::Task * task)
Register new task.
Parameters
task => CBuild::Task* -> pointer to staticly allocated task
Definition at line 126 of file register.cpp.
References CBuild::Task::self_name().
SetRebuildName()
void CBuild::Registry::SetRebuildName (std::string _name)
Set the rebuilt CBuild executable name.
Parameters
_name => std::string -> new CBuild user executable name
Definition at line 207 of file register.cpp.
Variable Documentation
cargs
std::vector<std::string> CBuild::Registry::cargs
Definition at line 113 of file register.cpp.
help
CBuild::Help CBuild::Registry::help
Definition at line 97 of file register.cpp.
Referenced by init().
initw
CBuild::Init CBuild::Registry::initw
Definition at line 98 of file register.cpp.
Referenced by init().
keywords
lib::map<std::string, std::string> CBuild::Registry::keywords
Definition at line 109 of file register.cpp.
largs
std::vector<std::string> CBuild::Registry::largs
Definition at line 114 of file register.cpp.
name
std::string CBuild::Registry::name = `CBuild.run`
Definition at line 111 of file register.cpp.
Referenced by CallTask(), and GetToolchain().
target_executed
lib::map<std::string, bool> CBuild::Registry::target_executed
Definition at line 107 of file register.cpp.
targets
lib::map<std::string, CBuild::Toolchain *> CBuild::Registry::targets
Definition at line 105 of file register.cpp.
task_executed
lib::map<std::string, bool> CBuild::Registry::task_executed
Definition at line 103 of file register.cpp.
tasks
lib::map<std::string, CBuild::Task *> CBuild::Registry::tasks
Definition at line 101 of file register.cpp.