CBuild::consts Namespace Reference
Constants.
Functions
std::regex cxx_line_comment (`//.*`)
Regex for stripping c++ line comments from file.
std::regex c_multiline_comment (`/\\*([\\s\\S]*?)\\*/`, std::regex_constants::multiline)
Regex for stripping c multiline comments from file comtent.
std::regex doxygen_comment (`/\\*\\*([\\s\\S]*?)\\*/`, std::regex_constants::multiline)
Regex for stripping doxygen comments from file comtent.
std::regex include_parser (`#include\\s+[\`<]([^\`>]+)[\`>]`)
Get include directives from file and parse file name in it.
std::regex check_type (`\\.(cpp|cxx|cc|c)`)
For checking for source file.
Detailed Description
Constants.
Function Documentation
c_multiline_comment()
std::regex CBuild::consts::c_multiline_comment (`/\\*([\\s\\S]*?)\\*/` , std::regex_constants::multiline)
Regex for stripping c multiline comments from file comtent.
Referenced by CBuild::get_file_data().
check_type()
std::regex CBuild::consts::check_type (`\\.(cpp|cxx|cc|c)`)
For checking for source file.
Referenced by CBuild::types::file::file().
cxx_line_comment()
std::regex CBuild::consts::cxx_line_comment (`//.*`)
Regex for stripping c++ line comments from file.
Referenced by CBuild::get_file_data().
doxygen_comment()
std::regex CBuild::consts::doxygen_comment (`/\\*\\*([\\s\\S]*?)\\*/` , std::regex_constants::multiline)
Regex for stripping doxygen comments from file comtent.
Referenced by CBuild::get_file_data().
include_parser()
std::regex CBuild::consts::include_parser (`#include\\s+([^\`>]+)` [\`<][\`>])
Get include directives from file and parse file name in it.
Referenced by CBuild::get_file_data().