CBuild Namespace Reference
Filebuffer for CBuild ecosystem.
Namespaces
namespace fs
namespace Registry
Classes
class cpp
Struct for saving properties of file.
class filebuff
Base class of filebuffer.
class GCC
class GXX
class Help
Help print task.
class Init
Init task.
class line_filebuff
class MINGW_GCC
class MINGW_GXX
struct Path
Path datatype.
struct Project_dependency
Project dependency data.
class str_filebuff
class Task
Task, can be runned from shell or code.
class Toolchain
Toolchain class.
Enumerations
enum stage { PRE
, POST
 }
Type of depencesies for toolchain.
enum build_type { EXECUTABLE
, STATIC_LIBRARY
, DYNAMIC_LIBRARY
 }
enum RType {
TASK
, BUILD
, RUN
, BUILD_RUN
,
DEBUG
, CLEAR
, REBUILD
, LOAD_DEPS
,
ERROR
 }
Run mode.
enum buffer_state { MATCH
, FILE_NEWER
, BUFFER_NEWER
 }
Represent atate of buffer.
enum color {
BLACK = 30
, RED = 31
, GREEN = 32
, YELLOW = 33
,
BLUE = 34
, MAGENTA = 35
, CYAN = 36
, WHITE = 37
 }
Text color.
Functions
RType parse (lib::map< std::string, std::string > *args, int argc, char **argv)
Parse arguments.
void loop (RType mode, lib::map< std::string, std::string > *args)
loop of CBuild
void rebuild (std::string scripts)
Rebuild userspace part of CBuild.
std::string get_version_string ()
Return version as string.
int get_version_major ()
Get major component of CBuild version.
int get_version_minor ()
Get minor component of CBuild version.
int * get_version_array ()
Get full CBuild version as int array of two components, no oveflow or rewrite check !
std::vector< std::string > parse_lines (std::string in)
Parse string to vector of strings.
void save_hashes (std::vector< std::string > hash_files, std::vector< std::string > code_files)
Check if saved hash match new hash of file and update saved hash.
std::vector< std::string > get_files (std::vector< std::string > files, std::string toolchain_id)
Get changed files.
void print (std::string msg, color fg=CBuild::WHITE)
Print colored text to STDOUT.
void print_full (std::string msg, color fg=CBuild::WHITE)
Print colored text to STDOUT if verbose flag is set.
void print_verbose ()
Enable verbose flag.
void system (std::string cmd)
Call stdlib system() and print cmd to shell.
std::string system_piped (std::string cmd, unsigned int buffsize)
Execute command and return it's output.
std::vector< std::string > * get_log ()
Get the internall command log.
std::regex comment_regex1 (`\\/\\/.*`)
std::regex comment_regex2 (`/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*/`)
std::regex include_search (`#include\\s+[\`<]([^\`>]+)[\`>]`)
std::string get_file_content (std::string path)
Get content of file, stripped from comments.
uint64_t hash (std::string path)
Get hash of file.
void save_hash_table (std::string toolchain)
Save hash table from map.
void load_hash_table (std::string toolchain)
Load hash table to map.
Variables
int version [] = {CBUILD_VERSION_MAJOR, CBUILD_VERSION_MINOR}
lib::map< std::string, uint64_t > hash_table_old
lib::map< std::string, uint64_t > hash_table_new
std::vector< CBuild::cpp > files
CBuild::cpp last_file_tmp
bool verbose = false
std::vector< std::string > log
Detailed Description
Filebuffer for CBuild ecosystem.
Author
WolodiaM (w_melnyk@outlook.com)
Date
Wed May 3 01:44:19 PM EEST 2023
@license GPL v3.0 or later
Copyright (C) 2022 WolodiaM This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/.
Enumeration Type Documentation
buffer_state
enum CBuild::buffer_state
Represent atate of buffer.
Enumerator
MATCH File match buffer.
FILE_NEWER File is newer, buffer is not updated.
BUFFER_NEWER Buffer is newer and file need update.
Definition at line 58 of file filebuff.hpp.
build_type
enum CBuild::build_type
Enumerator
EXECUTABLE
STATIC_LIBRARY
DYNAMIC_LIBRARY
Definition at line 51 of file Build.hpp.
color
enum CBuild::color
Text color.
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
Definition at line 33 of file print.hpp.
RType
enum CBuild::RType
Run mode.
Enumerator
TASK Run task.
BUILD Build target.
RUN Run target.
BUILD_RUN Build and run target.
DEBUG Build and run target in debug mode.
CLEAR Clear build output and cache.
REBUILD Rebuild user executable.
LOAD_DEPS Load other project deps.
ERROR Some error occurred.
Definition at line 33 of file CBuild.hpp.
stage
enum CBuild::stage
Type of depencesies for toolchain.
Enumerator
PRE
POST
Definition at line 50 of file Build.hpp.
Function Documentation
comment_regex1()
std::regex CBuild::comment_regex1 (`\\/\\/.*`)
Referenced by get_file_content().
comment_regex2()
std::regex CBuild::comment_regex2 (`/\\**\\*+(?:[^/*][^*]*\\*+)*/` [^ *])
Referenced by get_file_content().
get_file_content()
std::string CBuild::get_file_content (std::string path)
Get content of file, stripped from comments.
Parameters
path => std::string -> Path to file
Returns
std::string -> Content of file
Definition at line 177 of file hash.cpp.
References comment_regex1(), comment_regex2(), CBuild::cpp::cpp_path_abs, files, hash_table_new, hash_table_old, CBuild::cpp::hpp_paths_abs, include_search(), and last_file_tmp.
Referenced by hash().
get_files()
std::vector< std::string > CBuild::get_files (std::vector< std::string > files, std::string toolchain_id)
Get changed files.
Parameters
files => std::vector<std::string> -> List of code files (.cpp/.c)
toolchain_id => std::string -> Id of toolchain, to get hash file
Definition at line 269 of file hash.cpp.
References files, hash(), hash_table_new, hash_table_old, CBuild::cpp::hpp_paths_abs, last_file_tmp, load_hash_table(), print_full(), and save_hash_table().
Referenced by CBuild::Toolchain::gen_file_list().
get_log()
std::vector< std::string > * CBuild::get_log ()
Get the internall command log.
Returns
std::vector<std::string>* -> pointer to command log
Definition at line 54 of file system.cpp.
References log.
Referenced by loop().
get_version_array()
int * CBuild::get_version_array ()
Get full CBuild version as int array of two components, no oveflow or rewrite check !
Returns
int* -> array of two parst of CBuild version
Definition at line 615 of file CBuild.cpp.
References version.
get_version_major()
int CBuild::get_version_major ()
Get major component of CBuild version.
Returns
int -> major version of CBuild
Definition at line 613 of file CBuild.cpp.
References CBUILD_VERSION_MAJOR.
get_version_minor()
int CBuild::get_version_minor ()
Get minor component of CBuild version.
Returns
int -> minor (patch) version of CBuild
Definition at line 614 of file CBuild.cpp.
References CBUILD_VERSION_MINOR.
get_version_string()
std::string CBuild::get_version_string ()
Return version as string.
Returns
std:;string -> version of CBuild
Definition at line 612 of file CBuild.cpp.
References CBUILD_VERSION_STR.
hash()
uint64_t CBuild::hash (std::string path)
Get hash of file.
Parameters
path => std::string -> Path to file
Returns
uint64_t -> Hash of file
Definition at line 221 of file hash.cpp.
References get_file_content(), and hash().
Referenced by get_files(), and hash().
include_search()
std::regex CBuild::include_search (`#include\\s+([^\`>]+)` [\`<][\`>])
Referenced by get_file_content().
load_hash_table()
void CBuild::load_hash_table (std::string toolchain)
Load hash table to map.
Parameters
toolchain => std::string -> Toolchain id
Definition at line 258 of file hash.cpp.
References CBUILD_BUILD_DIR, CBUILD_HASH_DIR, CBUILD_HASH_FILE, and hash_table_old.
Referenced by get_files().
loop()
void CBuild::loop (CBuild::RType mode, lib::map< std::string, std::string > * args)
loop of CBuild
Parameters
mode => CBuild::RType -> from CBuild::parse function
args => lib::map<std::string, std::string>* -> args from CBuild::parse
Definition at line 282 of file CBuild.cpp.
References lib::map< _K, _D >::at(), BUILD, BUILD_RUN, CBuild::Toolchain::call(), CBuild::Registry::CallTask(), CBUILD_CACHE_DIR, CBUILD_COMPILE_COMMAND_JSON, CBUILD_COPY_CACHE_DIR, CBUILD_MAKEFILE, CBUILD_PROJECT_DEPS_DIR, CBUILD_PROJECT_DEPS_HEADERS, CBuild::Toolchain::clear(), CLEAR, CBuild::fs::create(), CBuild::Toolchain::debug(), DEBUG, CBuild::fs::DIR, ERROR, CBuild::fs::exists(), CBuild::fs::FILE, lib::map< _K, _D >::get(), get_log(), lib::map< _K, _D >::get_ptr(), CBuild::Registry::GetToolchain(), LOAD_DEPS, CBuild::Toolchain::load_project_deps(), log, MAGENTA, print(), print_verbose(), REBUILD, CBuild::fs::remove(), CBuild::Toolchain::run(), RUN, lib::map< _K, _D >::size(), and TASK.
parse()
CBuild::RType CBuild::parse (lib::map< std::string, std::string > * args, int argc, char ** argv)
Parse arguments.
Parameters
args => lib::map<std::string, std::string>* -> Returned arguments for other functions
argc => int -> argc from main
argv => char** -> argv from main
Returns
RType -> type of CBuild task
Definition at line 38 of file CBuild.cpp.
References BUILD, BUILD_RUN, CLEAR, lib::map< _K, _D >::clear(), DEBUG, ERROR, CBuild::Registry::init(), LOAD_DEPS, print(), lib::map< _K, _D >::push_back(), lib::map< _K, _D >::push_back_check(), REBUILD, RUN, and TASK.
parse_lines()
std::vector< std::string > CBuild::parse_lines (std::string in)
Parse string to vector of strings.
Parameters
in => std::string -> Input string
Returns
std::vector<std::string> -> Returned list of lines
Definition at line 39 of file filebuff.hpp.
Referenced by CBuild::line_filebuff::set_str().
print()
void CBuild::print (std::string msg, color fg = CBuild::WHITE)
Print colored text to STDOUT.
Parameters
msg => std::string -> text to print
fg => CBuild::color -> color of text
Definition at line 31 of file print.cpp.
Referenced by CBuild::Toolchain::call(), CBuild::MINGW_GXX::call(), CBuild::MINGW_GCC::call(), CBuild::Help::call(), CBuild::Toolchain::debug(), CBuild::MINGW_GXX::debug(), CBuild::MINGW_GCC::debug(), loop(), parse(), print_full(), CBuild::Toolchain::run(), CBuild::MINGW_GXX::run(), CBuild::MINGW_GCC::run(), system(), and system_piped().
print_full()
void CBuild::print_full (std::string msg, color fg = CBuild::WHITE)
Print colored text to STDOUT if verbose flag is set.
Parameters
msg => std::string -> text to print
fg => CBuild::color -> color of text
Definition at line 50 of file print.cpp.
References print(), and verbose.
Referenced by CBuild::Toolchain::gen_file_list(), and get_files().
print_verbose()
void CBuild::print_verbose ()
Enable verbose flag.
Definition at line 53 of file print.cpp.
References verbose.
Referenced by loop().
rebuild()
void CBuild::rebuild (std::string scripts)
Rebuild userspace part of CBuild.
Parameters
scripts => std::string -> path to scripts dir
Definition at line 601 of file CBuild.cpp.
References CBuild::Registry::GetRebuildArgs(), and system().
save_hash_table()
void CBuild::save_hash_table (std::string toolchain)
Save hash table from map.
Parameters
toolchain => std::string -> Toolchain id
Definition at line 241 of file hash.cpp.
References CBUILD_BUILD_DIR, CBUILD_HASH_DIR, CBUILD_HASH_FILE, and hash_table_new.
Referenced by get_files().
save_hashes()
void CBuild::save_hashes (std::vector< std::string > hash_files, std::vector< std::string > code_files)
Check if saved hash match new hash of file and update saved hash.
Parameters
hash_file => std::string -> path to hash file
code_file => std::string -> path to code file
Returns
true -> file hash equal to saved
false -> file hash different from saved
Load hash
Parameters
hash_files => std::string -> hash files
code_files => std::string -> code files
Returns
true -> file hash equal to saved
false -> file hash different from saved
Store hashes
Parameters
hash_files => std::vector<std::string> -> hash files
code_files => std::vector<std::string> -> code files
system()
void CBuild::system (std::string cmd)
Call stdlib system() and print cmd to shell.
Parameters
cmd => std::string -> command
Definition at line 35 of file system.cpp.
References BLUE, log, and print().
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::Toolchain::clear(), CBuild::Toolchain::debug(), CBuild::GXX::link(), CBuild::GCC::link(), CBuild::MINGW_GXX::link(), CBuild::MINGW_GCC::link(), CBuild::GXX::link_pack(), CBuild::GCC::link_pack(), CBuild::MINGW_GXX::link_pack(), CBuild::MINGW_GCC::link_pack(), CBuild::Toolchain::load_project_deps(), rebuild(), CBuild::Toolchain::run(), CBuild::MINGW_GXX::run(), and CBuild::MINGW_GCC::run().
system_piped()
std::string CBuild::system_piped (std::string cmd, unsigned int buffsize)
Execute command and return it's output.
Parameters
cmd => stt:;string -> command
buffsize => unsigned int -> Size of output buffer, malloc and fread
Definition at line 40 of file system.cpp.
References BLUE, log, and print().
Variable Documentation
files
std::vector<CBuild::cpp> CBuild::files
Definition at line 168 of file hash.cpp.
Referenced by CBuild::GXX::build(), CBuild::GCC::build(), CBuild::MINGW_GXX::build(), CBuild::MINGW_GCC::build(), CBuild::fs::dir(), CBuild::fs::dir_rec(), CBuild::Toolchain::gen_file_list(), get_file_content(), get_files(), CBuild::GXX::link(), CBuild::GCC::link(), CBuild::MINGW_GXX::link(), CBuild::MINGW_GCC::link(), CBuild::GXX::link_pack(), CBuild::GCC::link_pack(), CBuild::MINGW_GXX::link_pack(), and CBuild::MINGW_GCC::link_pack().
hash_table_new
lib::map<std::string, uint64_t> CBuild::hash_table_new
Definition at line 166 of file hash.cpp.
Referenced by get_file_content(), get_files(), and save_hash_table().
hash_table_old
lib::map<std::string, uint64_t> CBuild::hash_table_old
Definition at line 166 of file hash.cpp.
Referenced by get_file_content(), get_files(), and load_hash_table().
last_file_tmp
CBuild::cpp CBuild::last_file_tmp
Definition at line 170 of file hash.cpp.
Referenced by get_file_content(), and get_files().
log
std::vector<std::string> CBuild::log
Definition at line 32 of file system.cpp.
Referenced by get_log(), loop(), system(), and system_piped().
verbose
bool CBuild::verbose = false
Definition at line 28 of file print.cpp.
Referenced by print_full(), and print_verbose().
version
int CBuild::version[] = {CBUILD_VERSION_MAJOR, CBUILD_VERSION_MINOR}
Definition at line 610 of file CBuild.cpp.
Referenced by get_version_array().